#! /bin/bash

function help() {
	echo -e "\t-h | --help) display this help menu"
	echo -e "\t-f | --file) compress into .tar.xz"
	echo -e "\tfiles to compress --"
	echo
	echo -e "Usage: End the list of files to compress with '--'"
	echo -e "\t$0 [-f | --file] outputfile myfolder1/ myfolder2/ myfile1.txt myfile2.sh --"
}

FILE=""
FILES=""

if [ $# -gt 0 ]; then
	while ! [[ "$1" == "--" ]]; 
	do
		case "$1" in
			-f | --file)
				FILE=$2
				shift 2
				;;
			-h | --help)
				help
				exit 
				;;
			*)
				FILES="$FILES $1"
				shift 
				;;
		esac
	done
else
	help
	exit
fi

tar -cvf - $FILES | xz -9 -c -v - > $FILE.tar.xz
